image: cypress/base

cache:
  key: $CI_PROJECT_PATH
  paths:
    - _npm_cache

before_script:
  - npm config set cache "$CI_PROJECT_DIR/_npm_cache" --global

stages:
  - e2e-tests

test:
  stage: e2e-tests
  script:
    - npm install
    - npm run cypress:run
  artifacts:
    paths:
      - cypress/videos/*
      - cypress/screenshots/*
    expire_in: 4 week
    when: always
