name: End2End Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    # For docker images see:
    # https://github.com/cypress-io/cypress-docker-images/tree/master/browsers#cypressbrowsers
    container: cypress/browsers:node12.18.3-chrome87-ff82

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        npm install
        # npm run cypress:run
        xvfb-run ./node_modules/.bin/cypress run --browser chrome --headed
    - uses: actions/upload-artifact@v2
      if: always()
      name: Store videos
      with:
        name: Videos
        path: cypress/videos/
    - uses: actions/upload-artifact@v2
      if: always()
      name: Store screenshots
      with:
        name: Screenshots
        path: cypress/screenshots/
        if-no-files-found: ignore
