name: End2End Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "*/30 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    container: cypress/base

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        npm install
        npm run cypress:run
    - uses: actions/upload-artifact@v2
      name: Store videos
      with:
        name: Videos
        path: cypress/videos/
    - uses: actions/upload-artifact@v2
      name: Store screenshots
      with:
        name: Screenshots
        path: cypress/screenshots/
        if-no-files-found: ignore
