name: End2End Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    container: cypress/base

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        npm install
        npm run cypress:run
